name: Build & Publish Website

on:
  push:
    branches: [ master, develop, feature/* ]
  #pull_request:
    #branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  AZ_SVC_PRINCIPAL_UN: ${{ secrets.AZ_SVC_PRINCIPAL_UN }}
  AZ_SVC_PRINCIPAL_PW: ${{ secrets.AZ_SVC_PRINCIPAL_PW }}
  AZ_SUBSCRIPTION_TENANT: ${{ secrets.AZ_SUBSCRIPTION_TENANT }}
  AZ_RESOURCE_GROUP: ${{ secrets.AZ_RESOURCE_GROUP }}

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: dubsalot.azurecr.io/ci/azure
      credentials:
        username: ${{ secrets.AZ_SVC_PRINCIPAL_UN }}
        password: ${{ secrets.AZ_SVC_PRINCIPAL_PW }}
    env:
      BRANCH: ${{ github.ref }}
        
    steps:
      - uses: actions/checkout@v2
      
      - id: build_website
        name: build and compress
        run: |
          cd webui
          dotnet publish --output cibuild_o
          tar cfvz build.tgz cibuild_o
          ls -alF
      
      - id: upload-build-artifact
        uses: actions/upload-artifact@v2
        with:
          name: compiled-website
          path: "**/build.tgz"
  
  publish:
    runs-on: ubuntu-latest
    container:
      image: dubsalot.azurecr.io/ci/azure
      credentials:
        username: ${{ secrets.AZ_SVC_PRINCIPAL_UN }}
        password: ${{ secrets.AZ_SVC_PRINCIPAL_PW }}  
        
    steps:
      - id: publish_website
        name: display debugging info - variables
        run: | 
          echo "publishing website"
          az --version
          tfx --version



#----------------------------------------------------------------------------------------
#   do not need this right now, but leaving in place for future reference               #
#----------------------------------------------------------------------------------------
# services:
#   container_based_service:
#     image: dubsalot.azurecr.io/ci/azure
#     credentials:
#       username: ${{ secrets.AZ_SVC_PRINCIPAL_UN }}
#       password: ${{ secrets.AZ_SVC_PRINCIPAL_PW }}



#give me some more whitespace